import { Router } from "express";
import authRouter from "./AuthRouter.js";
import categoryRouter from "./products/CategoryRouter.js";
import productRouter from "./products/ProductRouter.js";
import colorRouter from "./products/ColorRouter.js";
import sizeRouter from "./products/SizeRouter.js";
import brandRouter from "./products/BrandRouter.js";
import cartRouter from "./CartRouter.js";
const router = Router();
router.use("/auth", authRouter);
router.use("/category", categoryRouter);
router.use("/products", productRouter);
router.use("/color", colorRouter);
router.use("/size", sizeRouter);
router.use("/brand", brandRouter);
router.use("/cart", cartRouter);
export default router;
